### ISSUE TITLE
Windowsとの互換性

### ISSUE THREAD

**Issue by 1217pond** [tonnetonne814/QuickVC-44100-Ja_HuBERT#1]
Windows上でtrain.pyを実行すると、`RuntimeError: Distributed package doesn't have NCCL built in`　というエラーが出ます。これは、NCCLがwindowsに対応していないのが原因です。私のデバイスはGPUを一台のみ搭載しているのでDDPは必要ありません。なので、DDPのシステムを無くしていただくことは可能でしょうか？　お願いします。

**Comment by 1217pond** [comment]
バックエンドを"gloo"に変更することで上記のエラーは消えましたが、
```Traceback (most recent call last):
  File "train.py", line 347, in <module>
    main()
  File "train.py", line 54, in main
    run(0,1,hps)
  File "train.py", line 129, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "train.py", line 151, in train_and_evaluate
    for batch_idx, (c, spec, y, f0, uv) in enumerate(train_loader):
  File "C:\Users\<user>\anaconda3\envs\QuickVC\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\<user>\anaconda3\envs\QuickVC\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\Users\<user>\anaconda3\envs\QuickVC\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Users\<user>\anaconda3\envs\QuickVC\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\<user>\anaconda3\envs\QuickVC\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\<user>\anaconda3\envs\QuickVC\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "<path>\QuickVC\QuickVC-44100-Ja_HuBERT-main\data_utils_new_new.py", line 208, in __call__
    f0_padded = commons.slice_segments_2dim(f0_padded, ids_slice , spec_seglen)[:,:-1]
  File "<path>\QuickVC\QuickVC-44100-Ja_HuBERT-main\commons.py", line 61, in slice_segments_2dim
    ret[i] = x[i, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (234) must match the existing size (228) at non-singleton dimension 0.  Target sizes: [234].  Tensor sizes: [228]
```
というエラーが新しく出ました。対処方法はありますでしょうか。
